### ISSUE TITLE
Viability of supporting orgmode

### ISSUE THREAD

**Issue by snoblenet** [OXY2DEV/markview.nvim#106]
Very cool indeed.

I'm wondering whether it would be viable to support other markup languages that have Treesitter grammars and similar types of entities.

In particular, I'm wondering whether it would be viable to support Orgmode.

**Comment by OXY2DEV** [comment]
The problem is that `tree-sitter` won't recognize nodes the same way.

![Screenshot_2024-08-14-09-25-36-080_com termux-edit](https://github.com/user-attachments/assets/a45608fb-a179-440b-99f9-b4e34a524444)
![Screenshot_2024-08-14-09-26-01-334_com termux-edit](https://github.com/user-attachments/assets/ef81d4d6-3af6-4501-87cf-db0cfbb4082e)

Same text, completely different syntax.

So, you have to make a new parser function for `org-mode`.

Of course, it's not impossible. It's just that it takes a while to do(more so because I have used `org-mode` only once)

**Comment by snoblenet** [comment]
Thanks for looking into it. I've been looking at myself. Orgmode has built-in export-to-HTML functionality, so it's probably simpler for me to piggyback on that with a plugin-free solution.
