### ISSUE TITLE
Feature Request : Latex Support

### ISSUE THREAD

**Issue by Divyanshg01** [OXY2DEV/markview.nvim#138]
Loving this plugin guys but It would be even cooler if it can support latex
Any plans or potential work arounds to have latex with this plugin?

**Comment by OXY2DEV** [comment]
I have never used latex so I have no experience working with it, so I am probably not the person you are looking for.

This would either have to be done via an external plugin(there should be a few listed in `awesome-neovim) or another cli tool(like the one `render-markdown` uses).

You can try and see if the latex plugins cause any issues with this plugin.

**Comment by Divyanshg01** [comment]
No issue 
One thing I would like to request you 
can you please provide the config files to make this plugin look like this ,since the default behaviour is different
![image](https://github.com/user-attachments/assets/d4467d01-ae48-4f95-815c-daa5d046bf61)

**Comment by OXY2DEV** [comment]
How does it look on your machine?

**Comment by OXY2DEV** [comment]
![Screenshot_2024-09-07-12-15-03-973_com termux-edit](https://github.com/user-attachments/assets/64d80287-ad23-48b8-8785-f39f0a576f14)


I have started working on this. So far, I have only added brackets to it.

But it should be possible without any external dependencies.

I also plan on letting users use other cli tool to do the latex → Unicode translation and show that with virtual lines.

**Comment by OXY2DEV** [comment]
I also added an option to add scopes to the brackets.

![Screenshot_2024-09-07-12-41-24-491_com termux-edit](https://github.com/user-attachments/assets/1d578466-7dc3-44d6-be9a-0e8bd57e22ad)

**Comment by kusnezoff-alexander** [comment]
Just wanted to through in [nabla.nvim](https://github.com/jbyuki/nabla.nvim), which seems to provide a similar feature, with the only difference being that the result is rendered in a floating window instead of being rendered inline. Maybe some inspiration could be drawn from there.

**Comment by OXY2DEV** [comment]
I honestly don't like using too many `virtual lines` as it gets distracting very quickly if you have a bunch of them on screen.

I would rather have something simple like this which doesn't get in the way.

https://github.com/user-attachments/assets/2714683d-cd52-4531-bf7b-617c103e5a36

**Comment by kusnezoff-alexander** [comment]
I am coming from Obsidian, so I am used to the "live-rendering" of LaTeX there. For me personally it would be really nice if the latex could be rendered just like it does there.

In the end it comes down to personal taste, but how are you then planning to render things like integrals/limes/matrices/... ?

**Comment by OXY2DEV** [comment]
Hmm. That's an issue too.

Guess I will have to see if a less *destructive* way to show them is possible.

**Comment by OXY2DEV** [comment]
@kusnezoff-alexander I have looked into the code of that plugin and I can only say that the approach that plugin is not exactly fast(it's checking a line letter-by-letter).

And I don't know about you but I would prefer not to do something like this as it can easily start making the entire redraw slower as it doesn't lavarge `tree-sitter` for the syntax.

For stuff like integrals, I would use something like this.

```lua
    ↓ Upper limit
∫ 0 ∞;
  ↑ Lower limit
```

I would then use highlighting to make it more *readable*.

Is it *perfect*? No, but then again, this is a *simple* markdown previewer so this should be a good enough sacrifice.

> Neovim runs in a TUI, so it makes sense to use all the features of a TUI rather than mimicking a GUI.

**Comment by kusnezoff-alexander** [comment]
[OXY2DEV](https://github.com/OXY2DEV) Ah oke, I thought it was leveraging `tree-sitter` (at least it says so in the README and I had to `:TSInstall latex` before I could use it).

Regarding your approach, I would say that it could be difficult if not impossible to manually render all of what LaTeX has to offer. Another idea would be to use an existing renderer (`pandoc`?) to render an image and then display the resulting image instead (it looks like [image.nvim](https://github.com/3rd/image.nvim) could be used for this)?

Honestly I don't understand your quote in this context, since a GUI is "is a form of user interface that allows users to interact with electronic devices through graphical icons and visual indicators such as secondary notation." [Wiki](https://en.wikipedia.org/wiki/Graphical_user_interface#:~:text=A%20graphical%20user%20interface%2C%20or,indicators%20such%20as%20secondary%20notation.). This feature restricts itself to visualization and doesn't include direct user interaction, or am I wrong?

**Comment by OXY2DEV** [comment]
> I thought it was leveraging tree-sitter.

It only uses Tree-sitter to get the text from the buffer(otherwise it would have to manually check everything line by line).

> Regarding your approach, I would say that it could be difficult if not impossible to manually render all of what LaTeX has to offer.

Just like `html`, I can only give you a simplified version to see. `Tree-sitter` doesn't tell me what a what `\frac{1}{2}` is. It only tells me that this is a `generic_command` so I have to manually add support for everything. And to make matters worse, `lua-patterns` isn't as powerful as regex so some edge-cases will go through.

So, the goal is to provide a *good enough* preview, instead of trying to support everything(which isn't possible, at least inside a terminal).

> Another idea would be to use an existing renderer (pandoc?) to render an image and then display the resulting image instead?

Wouldn't it be simpler to create a keybind that gets the text under the cursor(you can use tree-sitter too, if you want)? Then just send it to the terminal to run `pandoc` to get the image.

No idea how `image.nvim` gets the image but there should be some function to load an existing image from a path.

> Honestly I don't understand your quote in this context, 

I meant that unlike a GUI which has 100,000s of pixels to draw on the terminal only has a limited number of cells to draw on.

So something like 2<sup>2<sup>2</sup></sup></sup> can easily mess the rendering. Same goes for anything beyond `x/y`.

And aligning text is kind of a pain. There's too many `what-if` cases. For example, latex inside a `description list` wouldn't know where to place itself, nested `block quotes` would result in text being off by the a few characters, tables not retaining their structure when using latex inside them and so much more.

**Comment by Divyanshg01** [comment]
> How does it look on your machine?

Terminal : Kitty with Alabaster dark theme , transparency is enabled
This is how it  looks
I also use obsidian.nvim but I don't think that is the reason because I have disabled its ui features
![image](https://github.com/user-attachments/assets/3c99dc4f-d3d9-4b57-94fa-90f38e6f51c9)

my config look like this

```
return {
	"OXY2DEV/markview.nvim",
	lazy = false, -- Recommended
	-- ft = "markdown" -- If you decide to lazy-load anyway

	dependencies = {
		-- You will not need this if you installed the
		-- parsers manually
		-- Or if the parsers are in your $RUNTIMEPATH
		"nvim-treesitter/nvim-treesitter",

		"nvim-tree/nvim-web-devicons",
	},
	config = function()
		require("markview").setup({
			modes = { "n", "no", "c" }, -- Change these modes
			-- to what you need

			hybrid_modes = { "n", "i" }, -- Uses this feature on
			-- normal mode

			-- This is nice to have
			callbacks = {
				on_enable = function(_, win)
					vim.wo[win].conceallevel = 2
					vim.wo[win].concealcursor = "c"
				end,
			},
		})
	end,
}

```

**Comment by OXY2DEV** [comment]
@Divyanshg01 basically your `background` option is set to `dark`. But since you have a transparent background the plugin doesn't find a background color.

So, it looks through a bunch of fallback colors and one of them has a black background. This color is then mixed with other colors resulting in what you are seeing.

**Comment by Divyanshg01** [comment]
So is there a way to fix it without setting a opaque background of terminal ??
Also how to fix rendering of things like [!TIP] and [!DANGER]

**Comment by OXY2DEV** [comment]
A bit of an update on the issue.

![Screenshot_2024-09-08-09-04-59-783_com termux-edit](https://github.com/user-attachments/assets/4b4a9b6b-ac76-4f99-905e-22965fbf7fa5)
![Screenshot_2024-09-08-09-05-12-913_com termux-edit](https://github.com/user-attachments/assets/10a09395-3d6f-447d-bf93-063ef6fa929a)

I have also checked to see if I could do stuff like `integrals`. However, tree-sitter doesn't recognize them so there's really not much to do(at least without breaking something else).

**Comment by OXY2DEV** [comment]
Since I didn't mention why this issue was closed let me say it here.

1) Converting latex to `unicode` is quite problematic. Even `nabla` can only handle *some* cases so this approach isn't a solution.

2) Evaluating `latex` via `tree-sitter` also doesn't quite work as converting a `tree` to an `array` isn't easy especially if you need to add spaces to things for alignment.

3) Iterating letter by letter is quite slow and the plugin can redraw a few times per second(depending on how you configured it) which makes it a bad solution.

4) Virtual lines don't scroll horizontally so it doesn't look good when viewing on smaller windows.

5) There's no `latex to image` converter available in my package manager and building from source isn't possible for me so using images isn't possible for me.

6) even if we ignore the previous issue, images aren't supported in `termux` and `termux-x11` isn't great for typing so testing would take more time than it should.

> @Divyanshg01, for now I can only show primitive representations in the plugin. For example,
>
> ```md
> $\lim_{0 \to \infty}$
> lim_(0 → ∞)
>
> $\int_{2}^{3}$
> ∫₂³
> ```
