### ISSUE TITLE
✨ Feature: fold headers

### ISSUE THREAD

**Issue by moshpirit** [OXY2DEV/markview.nvim#147]
### The nature of the feature:

- [ ] Parser(syntax, conceal etc. related)
- [x] Renderer(style, options etc. related)
- [ ] Support(plugin support, language support etc. related)
- [ ] Other

### Description:

It would be great being able to fold the headers. 

**Expected behavior**: let's imagine we are at a header 4 piece of text. Being able to press `za` and toggle the folding text inside of it, including smaller headers (h5, and h6, but no other h4, h3, h2, or h1).

I'm newbie on nvim, so I apologize if it exists already how to do that.

**Comment by OXY2DEV** [comment]
You mean something like this?

https://github.com/user-attachments/assets/71b43ba2-abcf-4ac4-89c6-c6c5628c00a9

This doesn't work due to some issues.

1) Neovim doesn't have any events for opening/closing the folds. So the plugin doesn't update here 

2) You can't just *hide* lines so something needs to be shown.

3) This doesn't work if the heading has something like *Italic*, **bold**, `inline code` etc.

4) There's no straight way to do this(at least at the moment) and if you use this you will end up having a lot more folded then *just headings*.

5) You are going to need a custom foldtext which can be a pain to setup.

**Comment by moshpirit** [comment]
That was exactly what I meant. What a pity! TIL, thanks anyway!
How did you managed to get this to work if you don't mind the question?

**Comment by OXY2DEV** [comment]
> How did you managed to get this to work if you don't mind the question?

First, I inject some query that looks like this.

```query
; A section of text that starts with a heading should be folded

(section (atx_heading)) @mkv.fold
  (#set! @fold)

; "#set! @fold" allows stuff to be folded
```

Then, I set these options,

```lua
vim.o.foldmethod = "expr";
vim.o.foldexpr = "nvim_treesitter#foldexpr()";
```

> I am running these using `on_enable` callback so that it only happens when the plugin is enabled.

Now, for the text I have a plugin that allows creating custom foldtext based on the line where the fold started.

I use a this lua pattern to get the heading.

```
[#+](.*)$
```

> This gets everything after the # in a heading. The $ isn't needed so you can remove that if you want.

Then I just show this text on the fold.

**Comment by OXY2DEV** [comment]
If you don't know how to inject a query, I will be adding an option in the next commit(should be available pretty soon).

I will leave a link to that here.

**Comment by moshpirit** [comment]
Thank you!! Will definitely check into that next week!
