### ISSUE TITLE
Question: What are these things next to LineNr?

### ISSUE THREAD

**Issue by windowsrefund** [OXY2DEV/markview.nvim#169]
Greetings,

Having fun with this plugin but can't figure out what these things left to each header are?

![markview](https://github.com/user-attachments/assets/c04e2e7c-affb-4d46-9d2e-1e5178f408d4)

More importantly, how can I get rid of them? I don't see them in any of the screenshots and haven't found anything in the wiki.

Thanks in advance.

**Comment by OXY2DEV** [comment]
These are signs.

You can remove them like this.

```lua
headings = {
  heading_1 = { sign = "" },
  heading_2 = { sign = "" },

  setext_1 = { sign = "" },
  setext_2 = { sign = "" }
}
```

**Comment by windowsrefund** [comment]
Thanks, while I'm here, I just have to ask... why are these a thing to begin with and what is a `setext`? Seems like whatever is meant by `setext` would benefit from a more descriptive name and maybe all this stuff could be scoped at a higher level in order to keep things DRY.

Thanks again for the insight.

**Comment by OXY2DEV** [comment]
> why are these a thing to begin with

No reason really, but since no one's complaining I never changed them and.

> What is a setext?

Normally, people use `#` to create headings.

But you can also create them by making a `----` or a `=====` under the lines.

These headings are called `setext_headings`, so the options to configure them is called `setext_1` & `setext_2`.

> Seems like whatever is meant by setext would benefit from a more descriptive name.

They are literally called that, I don't name things.

Plus, you are almost never gonna use them. It's for people who still use the old markdown syntax and they would understand what `setext` could mean.

**Comment by OXY2DEV** [comment]
> all this stuff could be scoped at a higher level in order to keep things DRY.

Unfortunately, that comes at the cost of reducing customisability(which is the strong point of this plugin). Plus, you don't really need to set it for `setext_1` & `setext_2`, I included them in case someone comes across this issue in the future.
