### ISSUE TITLE
🐞 Bug: Padding for code blocks exceeds window width.

### ISSUE THREAD

**Issue by YodaEmbedding** [OXY2DEV/markview.nvim#188]
### Before reporting:

- [X] Ensure that the issue is reproducable on the main branch.
- [X] Ensure that there isn't an issue on this(either open or closed).

### Problem:

Code block exceeds the usable window width (`:echo getwininfo(win_getid())[0]["width"] - getwininfo(win_getid())[0]["textoff"]`).

![Actual](https://github.com/user-attachments/assets/c92fdb94-b679-42eb-aae9-5dbd3de34134)

### Steps to reproduce the issue:

Write the following in a window with usable width of 80:

```plain
Once upon a midnight dreary, while I pondered, weak and weary,
Over many a quaint and curious volume of forgotten lore—
    While I nodded, nearly napping, suddenly there came a tapping,
As of some one gently rapping, rapping at my chamber door.
“’Tis some visitor,” I muttered, “tapping at my chamber door—
            Only this and nothing more.”

It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of light, it was the season of darkness, it was the spring of hope, it was the winter of despair.

    Ah, distinctly I remember it was in the bleak December;
And each separate dying ember wrought its ghost upon the floor.
    Eagerly I wished the morrow;—vainly I had sought to borrow
    From my books surcease of sorrow—sorrow for the lost Lenore—
For the rare and radiant maiden whom the angels name Lenore—
            Nameless here for evermore.
```

### Expected behavior:

Something similar to this:

![Expected](https://github.com/user-attachments/assets/248a69ae-ce0f-4ad1-bc49-a45b29459a55)

This can be accomplished by only padding each line with the least possible *multiple* of the usable window width.

### Neovim version:

v0.10.1

**Comment by OXY2DEV** [comment]
That's an issue with `wrap` itself.

It can't be fixed since wrap doesn't count the *hidden* part of the lines. This results in the line being stretched instead.

**Comment by YodaEmbedding** [comment]
Couldn't it just output fewer characters on the shorter lines?

Example:

```plain
███Once upon a midnight dreary, while I pondered, weak and weary,███████████████
███Over many a quaint and curious volume of forgotten lore—█████████████████████
███    While I nodded, nearly napping, suddenly there came a tapping,███████████
███As of some one gently rapping, rapping at my chamber door.███████████████████
███“’Tis some visitor,” I muttered, “tapping at my chamber door—████████████████
███            Only this and nothing more.”█████████████████████████████████████
████████████████████████████████████████████████████████████████████████████████
███It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of light, it was the season of darkness, it was the spring of hope, it was the winter of despair.███████████████████████████████
```

Notice how each line is exactly a multiple of the "usable" window width (80 characters). The last line is 4*80 = 320 characters long.

Markview can redraw the output when the window size changes.

**Comment by OXY2DEV** [comment]
There's multiple things wrong with this approach.

1. Windows and buffers are not connected to each other. Multiple windows can contain the same buffer so it would be hard(and possibly not exactly performant) to constantly check for which window's size to use.

2. You can't really tell which line is *shorter*. If a code block uses a language that has conceals for it then getting the visible width of the line is next to impossible. And since `tree-sitter` can't be used for this lua patterns need to be used. But this can only manage simple syntaxes and is not fast on large code blocks.
3. The tree-sitter parser isn't quite *accurate*. So it ends up pulling other texts with it so calculating the width of the text has a large margin of error. Another issue is <tab> characters can interact with extmarks and can cause issues where texts get displaced instead.
4. To mitigate issue 3, the plugin uses `conceal` and as `wrap` doesn't count the conceals the text gets cut off mid-way. This also creates empty lines where the extmark is too large(e.g. an empty line inside the code block).

Also, even if those weren't the issue. Concealed text can sometimes be replaced with empty spaces(e.g. not enough window space, text being wrapped somewhere inside the concealed text).
> **This is considered an expected behavior.**
So, you will still have parts that are slightly off.

The best you can get is this.
![Screenshot_2024-10-22-08-54-26-410_com termux-edit](https://github.com/user-attachments/assets/bbfe538d-86f1-4ef1-b70b-d357b44cd23a)

**Comment by YodaEmbedding** [comment]
Perhaps a simpler option is to bound the area to some maximum number, after which no more █ padding characters are printed. This could be a config option, e.g. `config.code_blocks.max_width = 80`. Another possibility is to use (the first) `colorcolumn`; in this case, `colorcolumn=80`. Usually, windows are at least `colorcolumn` wide, and programmers usually keep code under e.g. 80 columns anyways.

Example implementation:

```diff
diff --git a/lua/markview/renderer.lua b/lua/markview/renderer.lua
index 7a47640..81fcb8a 100644
--- a/lua/markview/renderer.lua
+++ b/lua/markview/renderer.lua
@@ -1393,7 +1393,7 @@ renderer.render_code_blocks = function (buffer, content, config_table)
 			end_row = content.row_end - 1, end_col = content.col_end
 		});
 	elseif config_table.style == "minimal" or config_table.style == "block" or config_table.style == "language" then
-		local block_length = content.largest_line;
+		local block_length = math.min(content.largest_line, 80 - 3 * 2);
 
 		if type(config_table.min_width) == "number" and config_table.min_width > block_length then
 			block_length = config_table.min_width
```

Result:

![Quick test](https://github.com/user-attachments/assets/04191b21-e35d-46f0-a2f7-e5cd5e413403)

**Comment by OXY2DEV** [comment]
Wouldn't the most simplest solution be to just set `style="simple"`?

![Screenshot_2024-10-22-09-50-50-270_com termux-edit](https://github.com/user-attachments/assets/2702cf91-a41f-4a18-93f3-e1fdc749fde0)

**Comment by YodaEmbedding** [comment]
Ah, I wasn't aware of that.

```lua
require("markview").setup {
  code_blocks = {
    style = "simple",
  },
}
```

It's actually quite nice:

![style=simple](https://github.com/user-attachments/assets/253a0624-a704-4a54-a3ae-29ff82464c9e)
