### ISSUE TITLE
Display problem when line code in table

### ISSUE THREAD

**Issue by nanozuki** [OXY2DEV/markview.nvim#2]
Insert Mode:
![telegram-cloud-photo-size-1-5184061243676273634-y](https://github.com/OXY2DEV/markview.nvim/assets/4208028/f985635b-d6c4-4b10-a9ca-e6d2d4bce34d)

Normal Mode:
![telegram-cloud-photo-size-1-5184061243676273633-y](https://github.com/OXY2DEV/markview.nvim/assets/4208028/fb8fd74b-fbc2-4a8c-ac20-2620e9b87a3f)

ColorScheme: [zonbones](https://github.com/zenbones-theme/zenbones.nvim)

Config: default config.

File: https://github.com/folke/lazy.nvim/blob/4ea9fe060042f345960ad0c01aa7bca91405e10a/README.md?plain=1#L516

**Comment by OXY2DEV** [comment]
This is caused by a bug(actually 2 bugs) in the function that makes the table.

The first one(the separator being incorrectly aligned is due to placing whitespaces before/after the `---`. Treesitter considers them part of the `|` which is why it's in the wrong spot.

The second one is caused by backticks, when conceal level is used they `hide` some parts of the text. So, the function was supposed to calculate the visual width, unfortunately how it is done makes it prone to bugs.

---

But I am fixing them right now.

**Comment by OXY2DEV** [comment]
Update:

![Screenshot_2024-06-28-11-08-09-728_com termux-edit](https://github.com/OXY2DEV/markview.nvim/assets/122956967/3a9987e2-7ec4-4078-82cf-cd80f7031546)

I have made some changes to the code to fix the issue.

This should hopefully fix the issue.

**Comment by OXY2DEV** [comment]
This update should solve the issue(I hope).

Let me know if the issue still persists.
