### ISSUE TITLE
bug: cursor is not shown in inline code

### ISSUE THREAD

**Issue by dj95** [OXY2DEV/markview.nvim#33]
Hi,

first of all thanks for your awesome work on this plugin! It looks really great and adds a lot of fun working on documentation!

I experience one small issue. When in normal mode, the cursor jumps through inline codeblocks, such that single characters cannot be selected. Hopefully it's visible in the screen recording.

https://github.com/OXY2DEV/markview.nvim/assets/4348959/071b891e-058c-4cbe-9905-097206fb05d1

It's occurring on the dev and main branch. Here are the versions used:

neovim:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

markview: `7dd8bdbac48a5e314d682e4dd81f7e7251e5d0b4` (dev branch)
colorscheme: catppuccin

Please message me in case you need any further details.

Keep up the great work!

**Comment by OXY2DEV** [comment]
That's because they use `inline virtual text`. It's one of the drawbacks.

> Let me tell you the actual issue

The plugin uses `conceallevel` and neovim hides the backticks for inline codes so if I try to add padding to the text I may unintentionally remove other text.

This becomes a bigger issue when they are inside of tables(since I have no actual way to check how much text is concealed).

Which is a bit of a drawback.

I will have to rework on this eventually(to use `add_hl()` and `inline_virt_text()` together instead of this mess).

**Comment by dj95** [comment]
Thanks a lot for your fast reply and the details!

**Comment by OXY2DEV** [comment]
> Thanks a lot for your fast reply and the details!

I actually did push a change to how links & inline code blocks. It is available in the `dev` branch.

![Screenshot_2024-07-10-08-57-19-482_com.termux-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/8fe2b55a-7c33-4af2-b0be-402a396f708f)

**Comment by dj95** [comment]
Thanks a lot for the quick fix! It works like a charm
