### ISSUE TITLE
[Feature Request] View escaped characters without leading "\"

### ISSUE THREAD

**Issue by 22ispencer** [OXY2DEV/markview.nvim#44]
When converting files from html to markdown using pandoc, quotes (both single and double) are escaped with a "\\" prefix. Would it be possible to hide these leading slashes?

**Comment by OXY2DEV** [comment]
> When converting files from html to markdown using pandoc, quotes (both single and double) are escaped with a "\" prefix. Would it be possible to hide these leading slashes?

That's actually very hard to do since Tree-sitter doesn't really know where something is.

You can probably use `matchadd()`(you will need some robust regex for it or else it might not work).


Doing it inside the plugin can be hard since I will have to constantly check for them in `inline codes`, `links` , `tables` etc. at the same time I will have not conceal them in places like `code_blocks`.

It is not *really* performant to check every line(or else we wouldn't use Tree-sitter for everything). Plus it's hard to keep track of. Not to mention there are too many `what-ifs`.

This should probably be a *formatters* job since that's something they can do. So, you should probably look if any of the markdown formatters can achieve that.

**Comment by 22ispencer** [comment]
I'll look into it more, thanks for the quick reply!
