### ISSUE TITLE
Do we have this feature like markdown.nvim

### ISSUE THREAD

**Issue by letieu** [OXY2DEV/markview.nvim#58]
Markview.nvim is great, only issue is it make edit markdown harder sometime.

And I see markdown.nvim have this feature, I think may be we can I same

https://github.com/MeanderingProgrammer/markdown.nvim/commit/726c85cb9cc6d7d9c85af6ab093e1ee53b5e3c82#diff-4674e199eb49f6ab8497a756d69905e4a687de54ed4f504e3539c6a4a1695208

**Comment by OXY2DEV** [comment]
I will see what I can do.

**Comment by OXY2DEV** [comment]
https://github.com/user-attachments/assets/72a42269-7aae-40c5-bc4a-724ed331e883

here's an early version of this feature.

> Honestly I find this feature kinda useless since it unfortunately doesn't retain the strong point of either raw or preview mode. But it has the shortcomings of both of them.

If you are wondering why nested list items causes the parent item to also become unconcealed. It's because that's how `Tree-sitter` sees it and it looks much less obstructive(of course coming at the cost of becoming very hard to implement).

This also applies to code blocks and block quotes. They will be entirely unconcealed when the cursor is inside them.

**Comment by OXY2DEV** [comment]
![new_feature](https://github.com/user-attachments/assets/039e80e9-2e14-4072-9a00-c3addacaaa92)

@letieu, I have pushed a new commit to the **dev** branch. You can test it out to see any potential bugs(though they shouldn't occur).

>[!Note]
> It only works on `insert` mode. And you need to move your cursor to activate it when within certain blocks(e.g. Code blocks, block quotes etc.)

>[!CAUTION]
> This doesn't work when writing tables at the moment, so that's an issue.

**Comment by letieu** [comment]
Love it :)))

**Comment by OXY2DEV** [comment]
This issue will be closed now
