### ISSUE TITLE
feature: default highlight groups that can be used by colorschemes

### ISSUE THREAD

**Issue by folke** [OXY2DEV/markview.nvim#61]
### Is your feature request related to a problem? Please describe.

Right now, it's pretty much impossible to support this plugin in a colorscheme.

### Describe the solution you'd like

It would be great if this plugin could create default highlight groups that are linked to existing NEovim hl groups, instead of using the hl groups directly, so that colorschemes can override those groups.

Users could of course still decide to pick a custom group themselves.

### Describe alternatives you've considered

Right now, I'm using the config below, to at least re-use some existing groups:

```lua
{
    "OXY2DEV/markview.nvim",
    enabled = true,
    opts = {
      checkboxes = { enable = false },
      links = {
        inline_links = {
          hl = "@markup.link.label.markown_inline",
          icon = " ",
          icon_hl = "@markup.link",
        },
        images = {
          hl = "@markup.link.label.markown_inline",
          icon = " ",
          icon_hl = "@markup.link",
        },
      },
      code_blocks = {
        style = "language",
        hl = "CodeBlock",
        pad_amount = 0,
      },
      list_items = {
        shift_width = 2,
        marker_minus = { text = "●", hl = "@markup.list.markdown" },
        marker_plus = { text = "●", hl = "@markup.list.markdown" },
        marker_star = { text = "●", hl = "@markup.list.markdown" },
        marker_dot = {},
      },
      inline_codes = { enable = false },
      headings = {
        heading_1 = { style = "simple", hl = "Headline1" },
        heading_2 = { style = "simple", hl = "Headline2" },
        heading_3 = { style = "simple", hl = "Headline3" },
        heading_4 = { style = "simple", hl = "Headline4" },
        heading_5 = { style = "simple", hl = "Headline5" },
        heading_6 = { style = "simple", hl = "Headline6" },
      },
    },

    ft = { "markdown", "norg", "rmd", "org" },
  }
```

### Additional information

I'd love to add support to tokyonight.nvim and also would like to make this plugin the default for markdown rendering as a replacement of `headlines.nvim`, but only if the plugin has proper `colorscheme` support.

**Comment by OXY2DEV** [comment]
@folke sorry for the late reply, internet connection has just been restored in my area causing the late reply.

> It would be great if this plugin could create default highlight groups that are linked to existing NEovim hl groups, instead of using the hl groups directly, so that colorschemes can override those groups.

> I didn't add any `default` highlight groups simply because it was a pain to have set everything up every time I wanted to change the colorscheme. Plus a lot of the colorschemes simply don't set some highlight groups which is honestly a problem.

I am curious why colorschemes can't override these highlight groups?

The plugin uses `Colorscheme` event and `default=true` when setting groups so it shouldn't prevent colorschemes from adding their own colors instead.

---

But then again I am fairly new to plugin development so I could be wrong.

So, I am curious if there is something specific I should do so that it becomes easier to make it compatible with other colorschemes.

**Comment by ColinKennedy** [comment]
I'm a bit curious - Why not lean on the tree-sitter based highlight groups? e.g. this is my configuration:

```lua
    {
        "OXY2DEV/markview.nvim",
        config = function()
            vim.api.nvim_set_hl(0, "MarkviewHeading1", {link="@markup.heading.1"})
            vim.api.nvim_set_hl(0, "MarkviewHeading2", {link="@markup.heading.2"})
            vim.api.nvim_set_hl(0, "MarkviewHeading3", {link="@markup.heading.3"})
            vim.api.nvim_set_hl(0, "MarkviewHeading4", {link="@markup.heading.4"})
            vim.api.nvim_set_hl(0, "MarkviewHeading5", {link="@markup.heading.5"})
            vim.api.nvim_set_hl(0, "MarkviewHeading6", {link="@markup.heading.6"})
        end,
        ft = "markdown",
        dependencies = {
            "nvim-treesitter/nvim-treesitter",
            "nvim-tree/nvim-web-devicons",
        },
    }
```

## Before
![image](https://github.com/user-attachments/assets/ca936250-1ad4-4196-ad86-2ad2ed7c2642)

## After
![image](https://github.com/user-attachments/assets/54a85408-cf89-4726-b1b5-334ce40bdf2c)

Of course I'd tweak the colors more but linking seemed to help integrate an existing colorscheme

**Comment by OXY2DEV** [comment]
Because of a certain colorscheme.

For some odd reason that colorscheme decided to make every heading look the same.

Another reason is, **inconsistency**. Before the plugin would use something like `@comment.note` for notes.

But then I saw that sometimes some colorschemes wouldn't even have that highlight group.

So, it made no difference relying on `tree-sitter` highlighting if it comes with the same issue as the regular highlight groups.

**Comment by mawkler** [comment]
I would suggest using treesitter's `@markup.heading.X` when they exists, and otherwise falling back to default hard-coded highlight groups.

Moreover, I really like how markview creates a background highlight for each heading with the same color as `fg` but slightly darker. However, it seems like markview only does that for the default highlights based on diagnostics. Personally I would like it if I could just specify the `fg` for each heading level's highlight and have markview automatically create the slightly darker `bg`. From skimming the code I'm guessing that markview is using [`colors.mix()`](https://github.com/OXY2DEV/markview.nvim/blob/main/lua/markview/colors.lua#L177-L205) to create the `bg`?

**Comment by OXY2DEV** [comment]
>I would suggest using treesitter's @markup.heading.X when they exists, and otherwise falling back to default hard-coded highlight groups.

This doesn't work for colorschemes such as `kanagawa`. Trying to get the value of `@markup.heading.X` returns `@markup.heading` but trying `vim.fn.hlexists()` will return 0.

So, it bypasses all the logic leading to it making every heading look the same.

> Personally I would like it if I could just specify the fg for each heading level's highlight and have markview automatically create the slightly darker bg.

The reason for this is because not all colors mix well and using the % value doesn't always work. Of course you could argue that adding another option would fix that.

But at that point you are better off just making your own highlight groups.

**Comment by mawkler** [comment]
@OXY2DEV To me that just sounds like Kanagawa has chosen to only have one color for its headings. You can see [here](https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/highlights/treesitter.lua#L120-L127) that they've explicitly commented out the `@markup.heading.X` highlights. If Kanagawa wants multiple colors for different heading levels I think it's up to them to specify it.

But if you *do* want to enforce that the headings should have differing colors you could add a check for that as well, and fall back to a default highlight for any heading level highlight that is the same as `@markup.heading.1` for example.

I personally withhold that the `@markup.heading.X` is a healthy Neovim and Treesitter convention to follow.

**Comment by OXY2DEV** [comment]
> But if you do want to enforce that the headings should have differing colors you could add a check for that as well.

The problem is the plugin wouldn't know how to do that. Some `colorschemes` will just use `@markup.heading`, some of them `Normal` and who knows how many similar cases.

**Comment by mawkler** [comment]
@OXY2DEV I got this to work as a proof of concept using `vim.api.nvim_get_hl()`:

```lua
-- Fallback for headings 1 to 9
local fallback_groups = { "Title", "Special", "Identifier", "Statement", "Constant", "Function", "Type", "Keyword", "String" }

for i = 1, 9 do
  local markup_heading = "@markup.heading." .. i
  local markview_heading = "MarkviewHeading" .. i

  local hl_exists = vim.tbl_isempty(vim.api.nvim_get_hl(0, { name = markup_heading }))
  if hl_exists then
    vim.api.nvim_set_hl(0, markview_heading, { link = fallback_groups[i] })
  else
    vim.api.nvim_set_hl(0, markview_heading, { link = markup_heading })
  end
end
```

It links the `MarkviewHeadingX` to `@markup.heading.X` if it exists, and otherwise it links to a fallback group.

**Comment by OXY2DEV** [comment]
> It links the MarkviewHeadingX to @markup.heading.X if it exists, and otherwise it links to a fallback group.

Doesn't solve the issue since I know at least 1 colorscheme that likes to link some groups to `Normal` and I am not going to add a new check every time an exception occurs.

If the colorscheme still needs everything to look the same then they can just set the `MarkviewHeading...` groups to what they prefer.

**Comment by mawkler** [comment]
> I know at least 1 colorscheme that likes to link some groups to `Normal`

That sounds like an oddly configured colorscheme to me. But in my opinion it should be up to the colorscheme to specify its highlights. If a colorscheme wants all its headings to be highlighted `Normal`, shouldn't markview respect that?

**Comment by OXY2DEV** [comment]
Then I see people complaining about not looking like the screenshots(this has already happened once in reddit before).

**Comment by mawkler** [comment]
@OXY2DEV What was the final outcome? I couldn't find any info in the README 🙂

**Comment by OXY2DEV** [comment]
> @OXY2DEV What was the final outcome? I couldn't find any info in the README or in the commit history 🙂

**Colorschemes will handle changing colors**, the plugin will only *try* to match the colorscheme and will be using some default colors(taken from *catppuccin*) when all the fallbacks fail. Since,

1) Adding plugin support is already done by most colorschemes(and the community). So, there shouldn't be any need for this plugin to handle this.

2) Since most people wouldn't change their colorschemes often they can be just fine by just linking the plugins highlight groups to whatever they prefer this shouldn't be time consuming or hard(as far as I know).

3) The *dynamic* highlight groups is a useful feature to test how the plugin looks in various colorschemes so for people like me, who want to change the colorscheme but don't want to manually add support to unsupported plugins, this is a great feature.

4) I have no way to test colorschemes(especially ones that uses some type of transparency) this should be *good enough* solution. This is also the reason I can't add PRs for this plugin in other colorschemes.

5) Removing this may make people using older colorschemes to manually set everything up. As the plugin uses a lot of highlight groups this may cause more harm than good.

There are also some other minor reasons but these are the main ones.
